export default class CommonConstants {
  static readonly DIALOG_DEFAULT_HEIGHT: string = '210vp';
  static readonly DIALOG_EDIT_HEIGHT: string = '520vp';
  static readonly TINY_SIZE_IMAGE = {width: '28vp', height: '28vp'};
  static readonly MID_SIZE_IMAGE = {width: '36vp', height: '36vp'};
  static readonly FULL_LENGTH: string = '100%';
  static readonly TITLE_WIDTH: string = '60%';
  static readonly TITLE_HEIGHT: string = '10%';
  static readonly BACKGROUND_DEFAULT_COLOR: string = '#ff212325';
  static readonly FONT_DEFAULT_COLOR:string = '#fffefcfa';
  static readonly FONT_RANDOM_COLOR:string = '#ffff6f00';
  static readonly FONT_LIST_COLOR:string = '#ffeeffaa';
  static readonly LIST_DEFAULT_WIDTH: string = '93.3%';
  static readonly OPACITY_DEFAULT: number = 1;
  static readonly OPACITY_COMPLETED: number = 0.4;
  static readonly BORDER_RADIUS: number = 8;
  static readonly FONT_WEIGHT: number = 500;
  static readonly COLUMN_SPACE: number = 8;
  static readonly SHADOW_DEFAULT_CONFIG = { color: '#c6ffffff', radius: 8, offsetY: 2 };
  static readonly TODO_DATA: Array<string> = [
    "梳理",
    "上学",
    '打？？球',
    '运动',
    'MakeMusics',
    '遛狗',
    '学高数',
    '打电动',
    '再睡5分钟',
    '社交',
  ];
}
